/**
 * Script to decode Better Auth reset password tokens
 * Usage: npx tsx src/scripts/decode-reset-token.ts <token>
 */

import jwt from 'jsonwebtoken';

function decodeToken(token: string) {
  try {
    console.log("=== Token Decoder ===\n");
    console.log("Token:", token.substring(0, 50) + "...\n");

    // Try to decode as JWT
    try {
      const decoded = jwt.decode(token, { complete: true });
      
      if (decoded) {
        console.log("Token Type: JWT");
        console.log("\nHeader:");
        console.log(JSON.stringify(decoded.header, null, 2));
        console.log("\nPayload:");
        console.log(JSON.stringify(decoded.payload, null, 2));
        
        if (typeof decoded.payload === 'object' && decoded.payload !== null) {
          const payload = decoded.payload as any;
          
          if (payload.exp) {
            const expiryDate = new Date(payload.exp * 1000);
            const now = new Date();
            const isExpired = expiryDate < now;
            
            console.log("\nExpiry Info:");
            console.log("  Expires At:", expiryDate.toISOString());
            console.log("  Current Time:", now.toISOString());
            console.log("  Status:", isExpired ? "EXPIRED" : "VALID");
            
            if (!isExpired) {
              const timeLeft = Math.floor((expiryDate.getTime() - now.getTime()) / 1000 / 60);
              console.log("  Time Left:", timeLeft, "minutes");
            }
          }
          
          if (payload.email) {
            console.log("\nEmail:", payload.email);
          }
        }
      } else {
        console.log("Token Type: Not a JWT (possibly a random string)");
        console.log("Length:", token.length);
      }
    } catch (jwtError) {
      console.log("Token Type: Not a JWT (possibly a random string)");
      console.log("Length:", token.length);
      console.log("Format: Likely a random token generated by Better Auth");
    }

    console.log("\n=== End of Decode ===");
  } catch (error) {
    console.error("Error decoding token:", error);
  }
}

// Get token from command line args
const token = process.argv[2];

if (!token) {
  console.error("Usage: npx tsx src/scripts/decode-reset-token.ts <token>");
  process.exit(1);
}

decodeToken(token);
